### ISSUE TITLE
Best practice advice for multiple domains

### ISSUE THREAD

**Issue by niels-smoice** [atech/postal#101]
Hi,

we are a SaaS Company and send emails on behalf of your clients. 

We will not manage that every one adds SPF or DKIM.

What is best practice that the mail are not recognised as SPAM ?

THX and best wishes

Niels

**Comment by mattmartincouk** [comment]
It would be to add SPF and DKIM.

Messages will be signed using DKIM and if you don't have that, you'll find they nearly always will be marked as spam.

**Comment by adamcooke** [comment]
The best way to achieve this will be to set their address as the From address and use your own as the Sender. This will then sign the message using the DKIM from your own domain rather than requiring it on the actual from domain. 

You would need to enable this from the Admin page of the server though.
