### ISSUE TITLE
Exception when user does not add a header to a message

### ISSUE THREAD

**Issue by willpower232** [atech/postal#107]
If I don't add a header when sending an email over the API I get the following message:

> \`headers\` should be a \`Hash\` but is a \`Array\`

BUT I don't see this message because the PHP wrapper expects a `code` to be returned along with a `message`.

(two issues for the price of one?)

**Comment by adamcooke** [comment]
That looks like an error with the PHP library rather than with the Postal API itself. You are sending an array to the server and it should be a hash. If you send nothing, that won't be triggered. I don't know enough PHP to fix that quickly though!

**Comment by willpower232** [comment]
Unfortunately the library is https://github.com/atech/postal-php!

It looks like Postal API is not outputting a `code` with that particular error message which the exception thrower looks for when throwing the exception to the developer which causes an error that masks the exception.

Either appmail outputs a `code` or the wrapper library is very different.

Hope that makes more sense.

**Comment by adamcooke** [comment]
That's a parameter error which is different to the usual errors so might not be caught in the same way. The library needs fixing to make sure it sends a hash not an array which is the underlying cause here. I'll try and have a look at the library and see what needs to be done. We don't use PHP at all so we'd never encounter this ourselves hence why it exists.

**Comment by willpower232** [comment]
I don't mind having a go at the library as we'll be depending on it but obviously it would be good if Postal is consistent about its errors.

**Comment by adamcooke** [comment]
I believe it has been fixed in the postal PHP library. I don't know much about PHP but doing something that makes no sense to my Ruby brain seems to have fixed it.

The API does return consistent errors, you just need to know how to interpret them. See https://atech.github.io/postal-api/ for full details 😄

**Comment by willpower232** [comment]
Aha yes that looks like it would probably fix it! The link for the documentation will be handy too thanks.

I'll review this next week when I get a chance.

I might send a pull request for the exception I came up against to check the presence of the code before trying to use it if that sounds handy?

**Comment by adamcooke** [comment]
Please do! All pull requests welcome 👍
