### ISSUE TITLE
Invite Users Broken

### ISSUE THREAD

**Issue by asithade** [atech/postal#130]
When I try to send an invite to a user, the button remains stuck on loading and the following errors appear in console:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-8UwpdwiuqXJty4DoSWEA9W+FMdXW5Ol0a3ZjF7czsyo='), or a nonce ('nonce-...') is required to enable inline execution.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

```
The invited user doesn't get an email either to join.

**Comment by adamcooke** [comment]
Please can you take a look in the `log/production.log` when this occurs and see what error is being produced.

**Comment by asithade** [comment]
```
I, [2017-05-12T06:16:20.949862 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Processing by UsersController#create as JSON
I, [2017-05-12T06:16:20.949934 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]   Parameters: {"utf8"=>"✓", "invite"=>"", "organization_user"=>{"email_address"=>"myemail@gmail.com", "admin"=>"true"}, "commit"=>"Add User", "org_$
I, [2017-05-12T06:16:20.969745 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]   Rendering app_mailer/user_invite.text.erb
I, [2017-05-12T06:16:20.969921 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]   Rendered app_mailer/user_invite.text.erb (0.1ms)
I, [2017-05-12T06:16:21.120321 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Sent mail to asithade@gmail.com (149.9ms)
I, [2017-05-12T06:16:21.120668 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Completed 500 Internal Server Error in 171ms (ActiveRecord: 7.4ms)
F, [2017-05-12T06:16:21.121422 #2580] FATAL -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]
F, [2017-05-12T06:16:21.121472 #2580] FATAL -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Net::SMTPAuthenticationError (530 From/Sender name is not valid
```

**Comment by asithade** [comment]
```
I, [2017-05-12T06:16:20.949862 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Processing by UsersController#create as JSON
I, [2017-05-12T06:16:20.949934 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]   Parameters: {"utf8"=>"✓", "invite"=>"", "organization_user"=>{"email_address"=>"myemail@gmail.com", "admin"=>"true"}, "commit"=>"Add User", "org_$
I, [2017-05-12T06:16:20.969745 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]   Rendering app_mailer/user_invite.text.erb
I, [2017-05-12T06:16:20.969921 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]   Rendered app_mailer/user_invite.text.erb (0.1ms)
I, [2017-05-12T06:16:21.120321 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Sent mail to myemail@gmail.com (149.9ms)
I, [2017-05-12T06:16:21.120668 #2580]  INFO -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Completed 500 Internal Server Error in 171ms (ActiveRecord: 7.4ms)
F, [2017-05-12T06:16:21.121422 #2580] FATAL -- : [98465ffb-586b-4f2c-bdcf-4782484c9681]
F, [2017-05-12T06:16:21.121472 #2580] FATAL -- : [98465ffb-586b-4f2c-bdcf-4782484c9681] Net::SMTPAuthenticationError (530 From/Sender name is not valid
```

**Comment by adamcooke** [comment]
The from_name in your SMTP settings is wrong. You need to make sure it includes one of your domains.

**Comment by willpower232** [comment]
If you describe your settings and problem in a new issue, that would be the best thing.

**Comment by BlastFM** [comment]
I am unable to send or receive any email. Not sure what the problem is. My postal.yml settings are:
`web:
  # The host that the management interface will be available on
  host: blastfm.email
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address: 212.71.232.7

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  mx_records:
    - mail.blastfm.email
  smtp_server_hostname: mail.blastfm.email
  spf_include: spf.mail.blastfm.email
  return_path: rp.mail.blastfm.email
  route_domain: routes.mail.blastfm.email
  track_domain: track.mail.blastfm.email
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once
  # your installation has been set up.
  host: 127.0.0.1
  port: 25
  username: BlastFM Central Email Server
  password: hrAZtLFVaXSekdGcEdVZPp8t
  from_name: mail.blastfm.email
  from_address: post@blastfm.email

spamd:
  enabled: false
  host: 127.0.0.1
  port: 783

rails:
  environment: production
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: <hidden>`
I wondered whether it is because it is an unsupported TLD (blastfm.email?)

**Comment by willpower232** [comment]
Your username is wrong. It should be in the style `organisation/servername`. Click on the help link within the server you created that credential in.

Also you will probably want to change and remove that api key/password.

**Comment by BlastFM** [comment]
I need to change all of the passwords but I wanted to get it working first as the most important part.
I have created a new issue as suggested, thanks for your replies, appreciated.
