### ISSUE TITLE
AWS EC2 Warning

### ISSUE THREAD

**Issue by willpower232** [atech/postal#192]
As per https://forums.aws.amazon.com/thread.jspa?messageID=723498, sending emails from an EC2 instance requires you to ask Amazon to set up rDNS (Reverse DNS) for the IP addresses sending email from the server which makes the addresses static and takes them off the DUL blocklist.

It might be worth having a provider-specific page in the Wiki for this as postal users will experience deliverability issues until they ask Amazon to carry out the above.

For completeness, both IP addresses on our EC2 instance are Elastic IP addresses.

**Comment by elfeffe** [comment]
In my experience Digital Ocean is far better than Amazon for Postal, cheaper and better.

**Comment by willpower232** [comment]
I am actually a Digital Ocean customer and appreciate their awesomeness but in our corporate context, AWS is a much better fit and block list checking is a not publicised-enough factor when researching and becoming an email sender

**Comment by adamcooke** [comment]
Setting up RDNS is listed on the FAQ about message delivery. I don't really want to maintain a page of provider specific oddities. I'd hope a provider like Amazon would actually let you set your own PTR records for your IPs rather than needing to contact them.

https://github.com/atech/postal/wiki/FAQs#e-mails-sent-through-postal-are-going-to-spam
