### ISSUE TITLE
Threat-handling is inconsistent/dangerous

### ISSUE THREAD

**Issue by Naugrimm** [atech/postal#201]
I have enabled the scanning of messages via clamav and then proceeded to send a message containing the EICAR test string via the webinterface.

The result is as follows:

1. The message gets correctly labeled as a threat on the properties page:
![bildschirmfoto 2017-05-31 um 15 44 43](https://cloud.githubusercontent.com/assets/5753604/26634895/4e0adfb2-4618-11e7-8631-d69714dd872c.png)

2. **But** The `X-Postal-Threat` header is set to `no` and the message is passed:
![bildschirmfoto 2017-05-31 um 15 47 53](https://cloud.githubusercontent.com/assets/5753604/26635046/c929c97e-4618-11e7-9208-788b96abb1bd.png)

~~In `app/jobs/unqueue_message_job.rb` the `X-Postal-Threat`-header is only set when the spam score reaches the configured threshold, but the score of the message is never increased in `lib/postal/message_inspection.rb` in the `scan_for_threats` method.~~
**Edit:** This is not correct. According to the source, I would say the header **should** be set to `yes`, even if the spam score is below the threshold.

The quick fix is to modify the `scan_for_threats` method:

```ruby
      if data && data =~ /\Astream\:\s+(.*?)[\s\0]+?/
        if $1.upcase == 'OK'
          @threat = false
          @threat_message = "No threats found"
        else
          @threat = true
          @threat_message = $1
          # add a new "spam" check and increase this message's spam score
          @spam_checks << SPAMCheck.new("VIRUS", 100, $1)
          @spam_score += 100
        end
      else
        @threat = false
        @threat_message = "Could not scan message"
      end
```

The spam score for found threaths should be dynamically set well above the "Incoming Spam Failure Threshold" for this server, as you don't want to pass around anything that is detected as a virus.

Alternatively the behaviour is configurable via its own settings similar to the spam thresholds

**Comment by adamcooke** [comment]
Threats and Spam are totally separate, unreleated things in Postal. `X-Postal-Threat` will be set to the true if ClamAV reports any issues with the message. `X-Postal-Spam` is set based on thresholds on the account.

The virus checking is very simple at the moment and simply provided for information purposes. I'm sure we can expand its functionality to allow messages with viruses to be blocked entirely or filtered like spam messages.

However, I would have expected X-Postal-Threat` to be `yes` when it receives the EICAR message.

**Comment by catphish** [comment]
The issue here would seem to be that ClamAV is not detecting the threat, perhaps due to misconfiguration. I'd suggest we need to look more closely at how ClamAV is configured and used, starting with this specific case.

As Adam says, the spam score and the virus detection are unrelated features, and it would be up to the receiving application to make a decision based on both the spam and the virus flags, rather than just arbitrarily choosing one.

**Comment by ripkens** [comment]
To have the X-Postal-Threat header set to be true if ClamAV finds a Threat, one Line has to be changed in /app/jobs/unqueue_message_job.rb Line 132 

Old: "X-Postal-Threat: #{queued_message.message.threat == 1 ? 'yes' : 'no'}"
New: "X-Postal-Threat: #{queued_message.message.threat ? 'yes' : 'no'}"

The Problem is, that the mail inspection returns True || False not 1 or 0

**Comment by ripkens** [comment]
Additionaly, an extra header should be added:

"X-Virus-Status: #{queued_message.message.threat_details}"
