### ISSUE TITLE
Requirements for installing Postal

### ISSUE THREAD

**Issue by yeah-nothing** [atech/postal#231]
Did I read it right? I actually need 8 GB of RAM to run Postal? I created a Ubuntu 16.04 droplet at Digital Ocean with 512 RAM. I'm looking at the price structure of the Digital Ocean Droplets and it looks like a Droplet with 8 GB of RAM is $80.00 a month. With prices like that I might as well just use Mailchimp or Mailgun. Is there a cheaper way to run Postal?

Also somebody told me that Amazon uses mail filtering on Ec2. Is AWS a cheaper solution?

**Comment by stayallive** [comment]
I have fairly slow traffic running through Postal and am running it on 2GB RAM. Although this seems to be the lower limit, it's using about 1-1,5GB after startup (including MySQL and other services).

However, 8GB is recommended so keep an eye on it if you are running it on lower specced hardware.

Also if you are not willing to invest $80 monthly a self-hosted option might not be the solution for your use case since your time maintaining Postal should also be counted which adds on to the server costs.

**Comment by catphish** [comment]
8GB is indeed the recommended RAM for Postal, though many people run it successfully on 4GB. You may be able to adjust the number of processes (reducing them if your requirements are minimal), and disable unwanted features such as link tracking in order to use less memory.

We can't really offer any advice on hosted solutions, however if your requirements are not sufficient to run your installation, it may certainly be more cost effective to seek a hosted solution.

**Comment by ilyacherevkov** [comment]
Sorry for necroposting, do you think 2GB will be enough for 8-10K addresses and weekly newsletter?

**Comment by stayallive** [comment]
@ilyacherevkov it's not recommended as stated above. So the only way to know is to try for yourself 👍

**Comment by aaronstuder** [comment]
I am currently running this on a 2GB VPS with no issue, however my volume is very low (100 - 200 messages a day) - I want to use this more for relaying to my Mailcow, and stopping SPAM before it reaches the inbox.
