### ISSUE TITLE
Support for Spam Reports from ISPs

### ISSUE THREAD

**Issue by agnibha** [atech/postal#237]
We're trying to use Postal in our production environment. We understand that even 1/1000 emails being marked as spams has a significant impact on deliverability. Being able to track who reported Spam from ISPs, say, GMail/Yahoo/AOL is a must for us to stop sending further emails to them and maintaining good deliverability is of prime importance to us. Is there a way Postal handles that currently? I couldn't find it on the webhook interface or the documentation wiki. Any suggestion is welcome.

**Comment by mattmartincouk** [comment]
Registering for feedback loops from AOL/Yahoo/MicrosoftSNDS is a good way to go. Gmail hasn't got anything i'm aware of though.

Nothing to hook in just yet.

**Comment by anhofmann** [comment]
BTW: I found https://postmaster.google.com which should give information about spam rate for gmail.

**Comment by catphish** [comment]
As Matt says, the best option is to register with the SPAM feedback loops of as many providers as possible. This is unfortunately a rather manual process.

**Comment by rsgehlot** [comment]
I can't find any option to see how many emails are reported as spam in postal dashboard. Do we have any option available to display complaint reported

**Comment by catphish** [comment]
Unfortunately we don't yet have integration (ie automatic parsing) of spam feedback loops. You simply have to read this reports manually. We have always received so few that automating this has not been a priority. It may certainly be a useful feature to add one day.

**Comment by navinp** [comment]
I have a customer who claims he got his subscribers using landing pages. So I don't know if his list is 100% genuine. 

Nowadays there are so many services out there, that will help clean your list, and remove all emails that don't exist. 

So when this customers sends his emails, his bounce/hardfail/softfail will be very low, for me this will look like a good list, but if his list was purchased, he will have many spam complaints, that I will never see and that will hurt my business really bad.

If you have one or two customers, it can be easy to do this manually and count the emails, but if you get 50 customers (for example), a build-in tool to monitor this would be extremely helpful.

Amazon uses a < 0.1% spam complaint rate, and suspends accounts when it reaches 0.5%

How do they do it? :/ This option would be a life saver, because the system would just ban users that abuse it.

**Comment by mattmartincouk** [comment]
They will automate the bounces and various other methods and monitor. Really easy but Postal just does not do this.

You're free to play with the code, it's open but as @catphish says, it may be a feature to add one day.
