### ISSUE TITLE
how it handle possible ip blacklist

### ISSUE THREAD

**Issue by cocodrino** [atech/postal#34]
Hi!!..how are you?...we're currently using sendgrid with several domains basically for 2 reasons
1) email visual builder:  we can use templates and configure how the emails will look, that is great, probably in a future would be possible incorporate mosaic to postal or some alternative
2) blacklist: we're sure that the ip will be clean and the users could send emails at any moment, are there some possibility that our server will be blocked being added to one blacklist and we need to remove ourselves from these lists?...what could be the limitations about use your own server as email server?..

thank you!! have a good day and keep doing a great work

**Comment by adamcooke** [comment]
1. I don't really have any immediate plans to add something like this myself because we don't have any need for it ourselves.

2. If you manage your own lists well it is unlikely you'll end up on a blacklist. Obviously, if you send spam you could end up on a list. You can usually contact list owners and ask to be removed if you are added in error. There are pros and cons to both running your own server and using a third party cloud solution. With your own server you are responsible for IP rep but it seems many providers are moving towards a more domain-based reputation using DKIM and DMARC.

**Comment by ovizii** [comment]
Would it maybe possible to assign multiple IPs to the server running postal and have postal do some round-robin kinda sending so when one IP gets blacklisted one can stop postal sending through that IP until it has cleared from all blacklists?

**Comment by adamcooke** [comment]
Technically that would probably be possible but it would be better to avoid getting your IPs blacklisted to start with and get them un-blacklisted with whoever listed them. This is isn't something I'm going to be working on I'm afraid.

**Comment by ovizii** [comment]
OK but apart from the getting blacklisted part, isn't it better to be sending from a pool of IPs? I thought that#s what "bigger" companies like sendgrid and the likes to especially since I know some providers throttle you if you are sending too many emails from one IP to protect themselves from flooding.

**Comment by adamcooke** [comment]
Postal supports sending from pools of IPs although this isn't well documented yet and is disabled by default. I will get this documented.
