### ISSUE TITLE
Webhook Payload "sent_with_ssl" is false

### ISSUE THREAD

**Issue by mohan-nishit** [atech/postal#348]
Hi there!

Thanks for sharing Postal with us. It is an amazing piece of work!
I have an issue to report, which is, my webhooks are reporting to an API endpoint with all events payloads, but all payloads have the field "sent_with_ssl" as false.

Postal itself is working fine, and if I telnet to the postal server, with an `ehlo postal.mydomain.com` I  can see `250-STARTTLS`. Are the emails not being sent over SSL?

**Comment by mohan-nishit** [comment]
#272 Also mentions this issue.

**Comment by igerzog** [comment]
I am trying to resolve this issue at the real moment but still have no success. I will keep trying in the near days.

**Comment by shopglobal** [comment]
#330 related

---------- Forwarded message ----------

**Comment by igerzog** [comment]
Interesting solution. I will check it tomorrow. Thanks!

**Comment by igerzog** [comment]
Still not resolved. Any suggestions?

**Comment by igerzog** [comment]
Well, I have resolved the problem with the permanent `false` value of "sent_with_ssl" field. The reason is that the class of socket object being checked [here](https://github.com/atech/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/config/initializers/smtp_extensions.rb) to determine if the connection secured is not `OpenSSL::SSL::SSLSocket` but `Net::InternetMessageIO`.

In order to fix this I suggest to modify `tlsconnect(s)` from `Net::SMTP` by adding new variable `@secure_socket` that becomes `true` after successful SSL connection:
```ruby
  def tlsconnect(s)
    verified = false
    s = ssl_socket(s, @ssl_context)
    logging "TLS connection started"
    s.sync_close = true
    s.connect
    if @ssl_context.verify_mode != OpenSSL::SSL::VERIFY_NONE
      s.post_connection_check(@address)
    end
    verified = true
    @secure_socket = true
    s
  ensure
    s.close unless verified
  end
```
and then place it to the end of `smtp_extensions.rb`. The definition for `secure_socket?` simply transforms to:
```ruby
  def secure_socket?
    !!(@secure_socket)
  end
```
If it's ok with my suggestion I will prepare a commit for this fix 🙂
