### ISSUE TITLE
Data getting swept clean

### ISSUE THREAD

**Issue by agnibha** [atech/postal#353]
I had configured the postal settings to have 15 days of retention of messages, 7 days retention of raw messages and for up to 2GB of stored message. Yesterday, I had seen somewhere around 1.4GB being used in stored messages. But, it got cleaned entirely now leaving ~390KB of data with me. Most of even recent raw messages are gone. 

Also, during this event, looks like the server had stopped sending emails as well since there were around 90k requests during a few hours while the postal metrics tell me that only ~38k emails were sent in the whole of yesterday(I was using the "after:<date-time>" syntax to query this). I request help regarding the understanding of how Postal works in this scenario.

It would also be helpful to know when or how frequently the job runs to clean these emails.

**Comment by catphish** [comment]
Unfortunately, yes, if you have your retention set too low (ie less than the amount of email you send in a day), there is a potential for the cleanup process to delete email that hasn't been sent yet! It simply deletes one day of email at a time until things go back below the limit. Due to the fact that it deleted whole tables at once, there is no way to differentiate between completed vs queued messages, you just need to make sure the retention amount is large enough to prevent this.

**Comment by magicdrums** [comment]
How can the cleaning of the retention be forced?

Thanks!

**Comment by willpower232** [comment]
Are you after a clear out of older messages or do you want a blank slate within your Postal server?
