### ISSUE TITLE
it's too slow to finish this step "postal bundle /opt/postal/vendor/bundle"

### ISSUE THREAD

**Issue by infooer** [atech/postal#363]
i think my server's network  have some troubles because of network blocking . can i use a alternative method instead of this .

The following is what i run "postal bundle /opt/postal/vendor/bundle":
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching rake 11.3.0
Installing rake 11.3.0
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 0.8.1
Installing i18n 0.8.1
Fetching minitest 5.10.1

then  it can't have any other actions .

**Comment by willpower232** [comment]
You can find all the gems that need to be installed in the gemfile but I'm not sure if you'll be able to install them separately so that you don't have to download and install them all in one go.

A bigger concern would be if you are having issues downloading the software, your servers network may not be sufficient for your future email sending.

**Comment by infooer** [comment]
thanks ! I just used a new source for the gemfile,and finished it.

**Comment by catphish** [comment]
Woo
