### ISSUE TITLE
Is it possible to prioritize message queue?

### ISSUE THREAD

**Issue by ozanhazer** [atech/postal#443]
There are times when we need to send an urgent message while another message queue is in progress. Is it possible to put these urgent messages on top of the queue so that they won't wait for the other trivial messages to complete?

**Comment by willpower232** [comment]
This is not currently possible. If you are experiencing delays sending messages, you should experiment with the number of workers and increasing the specification on your server.

**Comment by alexroosenstein** [comment]
We experienced the same issue, with transactional emails being held up due to marketing emails being sent out at the same time.
Our solution was to add another outgoing IP, create 2 IP pools and use 1 IP pool for marketing emails and 1 IP pool for transactional emails.
Each outgoing IP seems to have it's own queue (correct me if I'm wrong), and so transactional emails were no longer delayed.

**Comment by ozanhazer** [comment]
@willpower232 we already have multiple servers and upgrading them according to the max. load is an avoidable expense that's why we want to delay trivial messages. I'll experiment with the separate IPs, thanks...
