### ISSUE TITLE
Postal Maintenance?

### ISSUE THREAD

**Issue by longhorninmd** [atech/postal#444]
Just wondering if anyone on here provides postal implementation & maintenance services?  If so, I'd like to discuss working with you...

**Comment by dsnopek** [comment]
After setting up postal for our company, I thought to myself, "This is sooo cool! Someone should start a consulting company that helps web development agencies setup and maintain this." :-) I think that'd be amazing! Sadly, that's not what we do...

**Comment by longhorninmd** [comment]
Unfortunately, I believe one of the reasons why atech took postal open source is that they realized what a nightmare it is to support when handling any type of larger volume.  I've seen that when the queue gets above 400k messages, it can just stop working, even despite multiple restarts.  Plus, who uses Ruby in this type of software where high performance is a constant requirement?  Uh, nobody...

**Comment by adamcooke** [comment]
The reason we made it open source was because we didn't have time to run it as a service ourselves and wanted to let people run it on their own servers and support it themselves. We use it internally ourselves without any issues (although we don't throw 400k messages at it simultaneously and never have - it was written for transactional e-mail rather than mailing lists)

There are plenty of high performance services running Ruby but this is neither time or place to discuss the scalability of Ruby. If your installation is struggling with 400k messages in the queue then the issue most likely isn't anything to do with Ruby and is a problem somewhere either in Postal itself or with the database or message queue.

If you want to run a high performance Postal cluster I'm sure that's possible but you will need to make sure you give it enough computing power and that your database services are suitably optimised to handle the load needed to process high volumes of messages. Don't expect to do this on a $20 virtual machine. We'd be happy to discuss it on a consultancy basis if you've got the time & money to invest in setting it up properly. Feel free to drop an e-mail to support@atechmedia.com and we can see what we can do to help.
