### ISSUE TITLE
IP Pools don't appear to be working

### ISSUE THREAD

**Issue by zpnielsen** [atech/postal#459]
Hi all,

Recent build a server in AWS with multiple elastic IP's. AWS handles the NAT, and I'm provided with multiple private IP's on ethernet subinterfaces.

After parsing through the logs and running a few tcpdump's, I'm not seeing any of the IP's being used to originate SMTP connections outbound.

Just to confirm, I've created the IP pools using the internal (locally bound) IP's on the server and assigned the IP pool to the server, with the rules. I did use the same hostname for each entry. Not sure if that's no bueno or what (they all fall under separate A-records for the same name.

I've tried different permutations of rules for the server-level IP pool assignment, (from/to address) as *.*, *.domain.com, domain.com. None seem to influence the use of the IP pool.

Apologies for not being able to provide much further insight. Any points you can provide would be much appreciated.

**Comment by zpnielsen** [comment]
Hah, never mind. I rebooted and it's working as expected now.

Guess I should've tried that first. I bounced it via postal restart, but I guess that just wasn't quite enough.

Thanks!

**Comment by ankitsamarthya** [comment]
Hi @zpnielsen,
I have deployed postal in AWS. I want to set up IP pool for the mail server. I tried assigning new private IPs to the ec2 instances and use those in the IP pool. Is this how we are supposed to configure it because it's not working. My messages are stuck in the queue.

Please help me with the correct guidelines to set this up. Thank you.

**Comment by maratgaliev** [comment]
@ankitsamarthya hey did you solve you issue? @zpnielsen can you help?
