### ISSUE TITLE
Mail Server?

### ISSUE THREAD

**Issue by wassimseif** [atech/postal#51]
Can this be used as a mail server? The introduction is not very clear. For example, i have a domain (mysupercooldomain.com). Can i run postal on a VPS and just use it as a regular mail server ? and use mail client (outlook...) to connect to it?

**Comment by jduncanator** [comment]
It _can_ receive incoming emails, however you will need to forward these on to somewhere else, for example another email address or mail server. Postal does not provide mailboxes or IMAP/POP3. You cannot connect to Postal and receive email messages via Outlook etc.

**Comment by ovizii** [comment]
I'm just wondering why postal has incoming email capability, is there a particular reason for this seeing that it doesn't offer mailboxes.

**Comment by adamcooke** [comment]
If you run a web application that needs to accept incoming e-mail you might use it with the HTTP endpoints to convert incoming emails into HTTP requests. You can also use it to redirect mail to other mail servers (either using SMTP or to another e-mail address).

**Comment by ConneXNL** [comment]
@adamcooke I now understand postal does not have IMAP support but how I don't understand how to make it useful for the common email use case.

For example: Is it possible to use a Gmail account to receive the messages to x@mydomain.com and to setup Gmail to send valid emails as x@mydomain.com via postal?

I still have a hard time to understand what role postal has and what it has not, and how and with what to integrate it to get common business email support (receive / archive incoming email support & send emails with a company domain).

**Comment by jduncanator** [comment]
@ConneXNL In Postal, you can setup routes that determine what happens when an incoming email gets received. They can either be turned into a Web request, or forwarded to another email address.

For example, if you sent out a mass email from the address "promo@mycompany.com", and wanted to forward replies to your mass email (that would be sent to promo@mycompany.com) to your own email address, you could setup an SMTP Route that forwards any emails received (incoming) to your email address. This means you no longer have to send emails from "noreply" addresses, and can appropriately handle responses.

It also allows you to handle cases when, for example, someone replies to a promotional email with the subject "Unsubscribe". Normally, this email would bounce, however you could pass this information onto a HTTP endpoint (via a webhook) that automatically unsubscribes people from your mailing lists.

Postal does _not_ store the incoming emails in a mailbox, and does not expose them via a MDA like Dovecot, nor should it. Postal is design to replace large scale mail delivery infrastructure that is used in web applications and send mass emails (on the scale of thousands to millions). It is not designed to replace your day to day email account (eg. Gmail), nor should you want to.

**Comment by ovizii** [comment]
So basically, say I have a working email domain and website, all hosted reliably, I could stop sending my newsletter from those resources and start using a 3rd party like sendgrid or roll my own with postal while continuing to use whatever service I use for my day to day emails, right? 
The benefit of postal vs. rolling my own postfix solution would be the possibility to create companies and users, the tracking, API, endpoints, etc. etc. ?

**Comment by jduncanator** [comment]
@ovizii Yes, that's correct. The benefit of Postal is the increased administrative control and insight you have into mail delivery vs that of a plain postfix install. It's basically postfix with a nice GUI and easy configuration.

I would say that, if you are sending a large set of emails, say anything past 50, you should be doing so via a service that is dedicated to doing that. Sending mass emails or newsletters from your own personal email account will only negatively impact the deliverability of your day to day email, and potentially your standing with your email provider (who may have rate limits in place).

A better solution would be to setup Postal (or sign up for the free plan of SendGrid unless you are relatively verse in Linux administration), and setup your domain in it. You can then add Postal or SendGrid's SMTP Relay as a send only email account with a dedicated email address in Outlook or another email client and use this to send your mass emails and newsletters.

Be aware that if you are sending any less than 1000 or so (probably even more), then you are much better off going with the SendGrid solution. Email is very vulnerable to a "warm up period" where receiving ISPs learn the quality of the emails coming from a certain service and/or IP address and are a lot more skeptical of emails coming from servers that they haven't seen a large quantity of email from yet. You'll also need to ensure that your own IPs stay off block lists, something SendGrid does for you.
