### ISSUE TITLE
Catch-all Endpoint Addresses

### ISSUE THREAD

**Issue by mattmartincouk** [atech/postal#57]
The end-point addresses want you to set an email address.

Is this explicitly required or can there be a substitute for * (as that does not work).

**Comment by adamcooke** [comment]
I'm not sure I understand. You should be able to use `*` on routes for incoming messages and send them to HTTP, SMTP or other addresses.

**Comment by mattmartincouk** [comment]
I've tried that again..

"Wildcard routes cannot be routed to SMTP servers or addresses"

*@domain.com

Going to a SMTP end point.

It seems from what you've replied with, it should be possible.

**Comment by adamcooke** [comment]
Oh. That was something we put in to prevent abuse. I can probably just remove that validation and allow wild cards to be used with any endpoint type.

**Comment by catphish** [comment]
This limitation was added because configuring a domain this way is often a bad idea. It causes a huge influx of spam when spammers try to guess valid email addresses (and succeed on every attempt). As @adamcooke says, this limitation can be removed now, but I'd recommend that perhaps a warning be left in the UI.

**Comment by jace** [comment]
How does one remove this limitation?

**Comment by mattmartincouk** [comment]
It was removed, hence the commit on 1st May and the closed status. Always worth reading any commits and the status.

**Comment by jace** [comment]
My bad. My week-old installation still had this code. I'll go check why it's outdated. Thanks for this fix.
