### ISSUE TITLE
Is it possible that postal send mail without add a domain?

### ISSUE THREAD

**Issue by Manishjodhani** [atech/postal#661]
Hi,
My query is i'm using two domain one is added in postal and records are verify but i will send mails with other domain using postal credentials.
And if mail is delivered then records are passed by verify domain.
Thanks in advance

**Comment by destroyer998** [comment]
You could use the sender header. There is an option in advanced settings to allow the usage of different domains, as long as you use the Sender header in emails. Be sure to keep check of the SPF records and such, otherwise you'll increase the spam scode.
![screenshot from 2018-09-17 13-40-38](https://user-images.githubusercontent.com/12081618/45621085-669d5500-ba7f-11e8-81d2-aa65745f96d5.png)

**Comment by Manishjodhani** [comment]
I try that but no use.
I found another solution for that :+1:
