### ISSUE TITLE
Can send emails, but cannot receive

### ISSUE THREAD

**Issue by chatchy** [atech/postal#662]
Hello,

My name is Smitty and I’ve recently attempted implementing Postal on my current domain.

There’s absolutely no issue when sending emails, but I cannot figure out incoming emails.

I’ve added the recommended dns configuration settings using Postal web and everything gets green check marks.

I did add additional records as described at  https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration,

but somehow, my email address I purchased previously stops responding.

The domain is chatchy.com and I have Postal running at webmail.chatchy.com, hosted at AWS.

I have been messing around with dns records as early as this morning, so propagation may be a factor but I have been dealing with this since last Thursday and it doesn’t seem like waiting for dns updates does the trick.

I know it would help to have Postal configuration and dns record details to better assist me, I’ll happily provide what’s requested.

Please let me know if any assistance can be provided and where I can receive solid feedback.

I really like this web service and I hope I can benefit fully from it.

Thank you in advance…

Smitty @chatchy

**Comment by willpower232** [comment]
Hello,

It doesn't look like any DNS records for webmail.chatchy.com exist.

Since you're hosting at AWS, you may need to configure your Security Groups to allow port 25 (or an alternative port) in. You will probably also need to enquire about reverse DNS so please have a look at https://github.com/atech/postal/issues/192
