### ISSUE TITLE
Run out of disk space

### ISSUE THREAD

**Issue by wh4u** [atech/postal#760]
Hello everyone.
I have a 120GB ssd disk for my postal installation.
Unfortunately mysql reached 110GB and we are running out of disk space.

Files /var/lib/mysql/postal@002dserver@002d1 is the bigger one.
What is the suggested method to empty this file ?

**Comment by willpower232** [comment]
Are you using the MariaDB installed with the script?
Have you made any configuration changes to it?
Is there any other software using the same database server?
Does one of your Postal mailservers have a lot of emails or attachments in it because the retention is high?

I don't think there is an easy way to clear up MySQL disk usage but I'm not a MySQL expert.

If your databases don't actually have that much data in, it might be prudent to stop Postal, migrate your existing databases to a new database server on a different VM, update Postals config, and start it. This will allow you to clear up the main server without ruining Postal but only if the problem isn't just how much data you are storing.
