### ISSUE TITLE
DNS设置

### ISSUE THREAD

**Issue by Yuaning** [atech/postal#776]
My server is only one public IP, I according to https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration's DNS
![image](https://user-images.githubusercontent.com/34407943/55082776-43fa9180-50dd-11e9-9b3e-02b57b1de5b7.png)
itself on the is not very understanding, I doubt the routes here
![image](https://user-images.githubusercontent.com/34407943/55082857-64c2e700-50dd-11e9-9b11-79e8a979996b.png)Why parsed into the back of the mx mail. Mail (the mx. Mail does not exist, right?)After logging into my page, SPF and dkim records are displayed and error is reported. I know there is an error, but I cannot find it. Please give me some advice.

**Comment by willpower232** [comment]
Ah that would seem to be a remaining bit of the problem from https://github.com/atech/postal/issues/615.

If I understand @catphish 's modification, you should be able to ignore the `mx.` part so what you need is an MX record with your main Postal domain in. So just `mail.whatever` instead of `mx.mail.whatever`.

**Comment by Yuaning** [comment]
I'm trying to resolve the routes of routes.Yeah, I found the ping routes.. mail.."Ping: unknown host routes. Mail ". Why the DNS configuration on GitHub is different from the advice on the web?Thank you very much
![image](https://user-images.githubusercontent.com/34407943/55124037-d0d63700-513f-11e9-9c9a-e078e0b01279.png)
![image](https://user-images.githubusercontent.com/34407943/55124071-ea777e80-513f-11e9-8d1e-349b474ebca6.png)

**Comment by Yuaning** [comment]
![image](https://user-images.githubusercontent.com/34407943/55124108-04b15c80-5140-11e9-9d0a-9fc9f468eec2.png)
As you can see, my domain name is already configured.

**Comment by Yuaning** [comment]
Thank you for taking time out of your busy schedule to reply to me and answer my questions. Thank you anyway

**Comment by willpower232** [comment]
I think you've slightly misunderstood how each domain is supposed to work.

The details from the wiki are for configuring the main domain pointing at your Postal server.

If your Postal server is called `postal.yourcompany.com` then you should create a TXT record `spf.postal.yourcompany.com` with the value `v=spf1 ip4:your.server.ip.address ~all`.

Then the domains you add to your Postal server need to include that so if you are adding `yourclient.com` to the Postal server, you should create a txt record for `yourclient.com` with the value `v=spf1 include:spf.postal.yourcompany.com`.

Also you should update your Postal config file to include `postal.yourcompany.com` instead of the default `example.com` domains otherwise it will never validate in the UI.

Does that all make sense?

**Comment by Yuaning** [comment]
Ok, I will try now. Thank you for your solution
