### ISSUE TITLE
Is it harmful to comment out check domain authentication?

### ISSUE THREAD

**Issue by TuguldurJ** [atech/postal#832]
Can I send a message using mismatch header information with domain?
So, I commented out this line and everything works well. But is it harmful? 
 
`authenticated_domain = @credential.server`
`.find_authenticated_domain_from_headers(@headers)`
`if authenticated_domain.nil?`
`return '530 From/Sender name is not valid'`
`end`

**Comment by willpower232** [comment]
I believe it allows you to send messages through Postal with any domain name on them, bypassing Postals checks on SPF, DKIM, etc.

It means its difficult to guarantee that the message will be delivered properly as failing the SPF and DKIM checks can result in your messages being marked as spam which can in turn lead to the blocking of your IP addresses by your recipients email systems.

If you aren't able to add the domains you are sending from to your Postal set up then you have other problems which should be resolved instead of removing this line of code.

**Comment by catphish** [comment]
I think there's a UI option to disable this check too.

**Comment by TuguldurJ** [comment]
@willpower232 thank you for reply,
I contemplated with How other Email Providers can send emails without configuring the customer's domain address and SPF, DKIM on their email server. How do they protect their IP address from SPAM? What about Sendgrid? or Mailchimp? What is the resolution for Postal MTA? If cannot, Why some guys comparing Postal MTA with Sendgrid? I know its open source, but sendgrid too if they remove their pricing. Please kindly say Important Truth. Thank you!

**Comment by catphish** [comment]
I'm afraid this question doesn't make sense to me. If you disable the checks, I believe Postal will still sign emails using its own domain name. It's not really a huge problem, but it's batter to use properly configured SPF and DKIM on a per-domain basis.
