### ISSUE TITLE
Support fast_server standalone deployment?

### ISSUE THREAD

**Issue by losingle** [atech/postal#859]
Our hardware does not support multiple external network ips. 
fast_server standalone deployment is required.

**Comment by willpower232** [comment]
I believe you have two choices, you can either

1. reconfigure your main Postal server so that the UI and API are on a different port allowing the `fast_server` can bind to the IP address as it wants (I think this is discussed in another issue)

or

2. you could duplicate your copy of Postal to new hardware that can connect to the same Rabbit MQ and MySQL server and edit the Procfile so only certain parts of Postal run on it (no one has discussed this AFAIK but I'm not aware of any reason it wouldn't work)
