### ISSUE TITLE
SOFT FAIL: Google Compute Engine port 25 block work around?

### ISSUE THREAD

**Issue by danthegoodman1** [atech/postal#864]
So I know that GCP blocks port 25. However, different from #461, I am not looking to connect in but send email out. Just sending email out fails because I believe it is trying to go out on port 25, so it just times out trying to send saying it can't find an smtp:
![image](https://user-images.githubusercontent.com/17806508/62589657-f31f5480-b897-11e9-8421-845994ce1094.png)
(This happens for any email)

When I ran on a DO server it worked fine, but since the IPs were listed on SPAMHAUS I had to move to GCP.

Commands like `telnet glockapps.com 25` fail but on port 465, 587, etc. they succeed.

Essentially I am asking if there is anyway to change the port it goes out on to either 465 or 587. I haven't had much luck internally routing it.

Edit:
running `postal test-app-smtp st-3-2d0ywnv2fx@glockapps.com` returns:
```Message was not delivered successfully to SMTP server.
Error: Errno::ECONNREFUSED (Connection refused - connect(2) for "127.0.0.1" port 2525)

  SMTP Host: 127.0.0.1
  SMTP Port: 2525
  SMTP Username:
  SMTP Password:
```
Not sure if it has relevance.

**Comment by willpower232** [comment]
If GCP is stopping your server from accessing other servers on port 25 then you are probably out of luck. Were you running that telnet command from your server? (see also https://github.com/atech/postal/issues/857#issuecomment-514589582)

**Comment by danthegoodman1** [comment]
@willpower232 how does postal communicate with smtp servers like gmail when they expect incoming mail in the higher port numbers then? Will it handle that?

**Comment by theel0ja** [comment]
>Port 25 is always blocked and cannot be used, even through an SMTP relay using G Suite.

https://cloud.google.com/compute/docs/tutorials/sending-mail/

**Comment by dekim** [comment]
Hello!

Can we change Postal to use another port as default? Since 25 is blocked, but we can use another port.

> By default, Compute Engine allows outbound connections on all ports but port 25, which is blocked because of the risk of abuse. All other ports are open, including ports 587 and 465.

**Comment by theel0ja** [comment]
@dekim No, as server-to-server connection always uses port 25/tcp. You should instead use some other hosting provider, since Google Compute Engine doesn't support sending email without a third-party service.

**Comment by dekim** [comment]
@theel0ja Do you guys have a recommendation on that matter?

All major cloud provider seems to block it.

**Comment by theel0ja** [comment]
At least Hetzner (by default), Linode ([by request](https://www.linode.com/2019/11/05/a-new-policy-to-help-fight-spam/)) and Vultr ([by request](https://www.vultr.com/docs/what-ports-are-blocked)) have outgoing port 25 open.

**Comment by Michael-Williams49** [comment]
I figured out that GCP VM is only blocking outgoing traffic from SMTP port 25, as clearly stated in google doc. But it does not mention blocking incoming traffic to port 25 of the VM instance. And according to my testing, postfix listening on port 25 indeed pickup external emails. So the only thing to be worked around is this outgoing traffic on port 25. You can set postfix to be working on port 26 (or whichever port), so that it receives and sends email on port 26, while setting incoming port forwarding with iptables to forward incoming traffic on port 25 to port 26. I tested this with `telnet mail.mydomain.com 25` and it was successful.

So here is the solution.
1. Configure postfix to work on port 26 (or any other port) by default. 
`sudo nano /etc/postfix/master.cf`
find the following line
```master.cf
smtp      inet  n  -  n  -  -  smtpd
```
replace it with 
```master.cf
26      inet  n  -  n  -  -  smtpd
```

2. Allow IP forwarding on your server
sudo nano /etc/sysctl.conf
find and uncomment the line
```sysctl.conf
net.ipv4.ip_forward=1
```

3. Configure port forwarding to forwarding incoming traffic on port 25 to port 26, as postfix is working on port 26. I have ufw on my server, you may also modify /etc/sysctl.conf (not tested) instead if you have no ufw on system. 
sudo nano /etc/ufw/before.rules
```before.rules
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 25 -j DNAT --to-destination :26 
COMMIT
```
