### ISSUE TITLE
Config for STARTTLS

### ISSUE THREAD

**Issue by muichkine** [atech/postal#98]
Hello,

What is the expected postal.yml config file parameters for using STARTTLS ?

```
smtp:
  host: smtp.office365.com
  port: 587
  evented: true
  log_connect: true
  username: my@email.com
  password: MyPassw0rd
  from_name: My Name
  from_address: my@email.com
  ssl_mode: STARTTLS
```
?

If I understand properly, this configuration in the postal.yml  is only for mails sent from the portal.
How can I set this up from the interface for a created mail server ?

**Comment by catphish** [comment]
In order to enable TLS, you will need a certificate and key. Once you have these, you can configure the SMTP server as follows:

```
smtp_server:
  tls_enabled: true
```

By default, Postal will look for the key and certifate in `config/smtp.key` and `config/smtp.crt` but you can configure this also if desired:

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: config/smtp.crt
  tls_private_key_path: config/smtp.key
```

**Comment by muichkine** [comment]
Isn't there a difference between TLS and STARTTLS ? I see one in the code:

https://github.com/atech/postal/blob/2f0155747c5c058afb83856ce5c3c8d5f8cad341/app/models/smtp_endpoint.rb#L27

**Comment by adamcooke** [comment]
You appear to be mixing configuration options there. You're adding things into the `smtp` section which simply defines where the application will send its outgoing messages. Things like `ssl_mode` and `log_connect` are not valid there - they belong under `smtp_server`.

You probably should be configuring your `smtp` to point to a mail server within your Postal installation rather than Office 365 though. Once you have it installed, you can simply create a new mail server, set the host to `localhost` and the password to some credentials from Postal.

**Comment by muratcorlu** [comment]
What is the default port for TLS connection when it's enabled? I couldn't use smtp_servet with tls support. Can you give a full postal config and client parameters examples about using tls on postal?

**Comment by catphish** [comment]
@muratcorlu the SMTP server supports `STARTTLS` which runs on the same port as normal SMTP.

**Comment by sandeep28saxena** [comment]
Hello, I enabled STARTTLS in postal.yml with configuration 

smtp_server:
  tls_enabled: true

and also put my domain's config/smtp.key and config/smtp.crt

but my email application shows below error while connecting and not able to connect on TLS/STARTTLS :+1: 

SMTP Error: Could not connect to SMTP host.
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Connection: opening to mail1.mypostaldomain.com:25, timeout=30, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ),)
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 mail1.mypostaldomain.com ESMTP Postal/TKEG5W"
SERVER -> CLIENT: 220 mail1.mypostaldomain.com ESMTP Postal/TKEG5W
CLIENT -> SERVER: EHLO emails2.myemailclientdomain.com
SMTP -> get_lines(): $str is "250-My capabilities are"
SMTP -> get_lines(): $data is "250-My capabilities are"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-My capabilities are250-STARTTLS"
SMTP -> get_lines(): $str is "250 AUTH CRAM-MD5 PLAIN LOGIN"
SERVER -> CLIENT: 250-My capabilities are250-STARTTLS250 AUTH CRAM-MD5 PLAIN LOGIN
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $str is "220 Ready to start TLS"
SERVER -> CLIENT: 220 Ready to start TLS
CLIENT -> SERVER: QUIT
SERVER -> CLIENT:
SMTP ERROR: QUIT command failed:
Connection: closed

Any clues what can be wrong ?

**Comment by igerzog** [comment]
If I am not mistaken the default file name for smtp certificate is `smtp.cert` and not `smtp.crt` as it is mentioned in postal defaults. Try to change file extension first.

**Comment by sandeep28saxena** [comment]
Hey @igerzog that indeed solved the issue. Thanks a lot. Could you please also let me know which page you are referring to for postal defaults ?

**Comment by igerzog** [comment]
Glad to hear that the issue is solved. The defaults are stated here: [postal.defaults.yml](https://github.com/atech/postal/blob/2a9702ba475b4703540e3edbe9de702b6f4a1dbe/config/postal.defaults.yml)

**Comment by sandeep28saxena** [comment]
But this page lists it as .crt and not .cert. Though for me .cert working now. 

smtp_server:
  port: 25
  tls_enabled: false
  tls_certificate_path: # Defaults to config/smtp.crt
  tls_private_key_path: # Defaults to config/smtp.key

**Comment by igerzog** [comment]
Yes, there is a mistake on this page. But if you look at the fast server section you can find the correct certificate extension. So I had taken the idea and changed `smtp.crt` to `smtp.cert` like `fast_server.cert`

**Comment by willpower232** [comment]
Thats a good spot @igerzog, seems theres mostly `.cert` but a few `.crt` crept into the code at some point in the past.

Did you want to make a pull request to remove the `.crt`'s to avoid future confusion?

**Comment by catphish** [comment]
Thanks for spotting this. If someone makes a pull request to standardize it that would be great.

**Comment by igerzog** [comment]
Ok, I have prepared the fix for cert file name. #350

**Comment by willpower232** [comment]
Thanks @igerzog there are a couple of other `.crt`'s in the codebase that you should be able to change to `.cert` to completely standardise it if you wouldn't mind :-P

https://github.com/atech/postal/search?utf8=%E2%9C%93&q=crt&type=

**Comment by igerzog** [comment]
Well ok :)

**Comment by igerzog** [comment]
Have just created new pull request. All files changed to `.cert` - #354

**Comment by willpower232** [comment]
@catphish the install zip https://postal.atech.media/packages/stable/latest.tgz still contains a reference to crt in the nginx bits somewhere so the install script doesn't work

**Comment by catphish** [comment]
I think this just means nobody's made a build recently. I assume this needs to be done manually.

**Comment by willpower232** [comment]
Ah fair enough, hope one of you can get your internal builds back in sync with github!

**Comment by SimonBiggs** [comment]
For those who come here via Google search, here is my postal config where I am pointing to the caddy generated certificates:

```yaml
smtp_server:
  # Specify configuration to the Postal SMTP server
  tls_enabled: true
  tls_certificate_path: /opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/postal.assistance.chat/postal.assistance.chat.crt
  tls_private_key_path: /opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/postal.assistance.chat/postal.assistance.chat.key
  port: 25
```

**Comment by willpower232** [comment]
Please note that when using lets encrypt certificates, be they from caddy or otherwise, you will need to restart Postal SMTP before the certificate expires every 3 months otherwise you will experience issues.

**Comment by SimonBiggs** [comment]
Thanks @willpower232, I massively appreciate that. I'll schedule a 3 monthly restart within the certificate renew window with cron.

**Comment by iampnp** [comment]
anyone else having trouble. make sure to issue RSA Key instead of ECC. caddy issued ECC and it didn't worked when i check the "postal logs"

so i did

`root@host1:~# sudo certbot certonly --standalone -d postal.yourdomain.com --key-type rsa
cp /etc/letsencrypt/live/postal.yourdomain.com/fullchain.pem smtp.cert
cp /etc/letsencrypt/live/postal.yourdomain.com/privkey.pem smtp.key
root@host1:/opt/postal/config# ls -lht
`

verify it
openssl s_client -starttls smtp -crlf -connect postal.yourdomain.com:25

handy site for testing -> https://www.gmass.co/smtp-test

**Comment by willpower232** [comment]
Please note Postals support for non-RSA certificates was fixed in #2126 so will be available in the next release.

**Comment by germanllop** [comment]
There is no automatic way to do this?

**Comment by david-brombacher** [comment]
I need some help getting STARTTLS and SSL working - thank you all in advance

I have made a new postal installation some weeks ago, version 2.1.4 on Ubuntu 22 TLS. I took over the SQL-Databases from the previous server running 1.x
After i got that basically working, i upgraded to the current release 2.3.1.
Caddy is running in a docker container (as suggested by the installation instructions)

For SSL/TLS/STARTTLS i did the following:

`ln /opt/postal/caddy-data/certificates/acme-v02.api.letsencrypt.org-directory/postal.my-domain.com/postal.my-domain.com.crt /opt/postal/config/postal.my-domain.cert`
`ln /opt/postal/caddy-data/certificates/acme-v02.api.letsencrypt.org-directory/postal.my-domain.com/postal.my-domain.com.key /opt/postal/config/postal.my-domain.key`
`chmod 644 /opt/postal/config/postal.my-domain.com*`

This covers the change of the extension for the certificate from .crt to .cert
After i upgraded to 2.3.1. i deleted the certificates to get new ones. I believe there is no need to go into caddy to make sure its RSA certificates, because that should be fixed in this version of postal.

In the postal.yml:

smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /config/postal.my-domain.com.cert
  tls_private_key_path: /config/postal.my-domain.com.key

I did postal stop/start and reboots afterwards, but the situation is:

Result from [https://www.gmass.co/smtp-test](https://www.gmass.co/smtp-test)

TLS is working:

`Connected to smtp://postal.my-domain.com:25/?starttls=always
<< 220 postal.my-domain.com ESMTP Postal/AF6SGB
>> EHLO [172.31.11.248]
<< 250-My capabilities are
<< 250-STARTTLS
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> STARTTLS
<< 220 Ready to start TLS
>> EHLO [172.31.11.248]
<< 250-My capabilities are
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> AUTH CRAM-MD5
<< 334 PDJmMGVjODMxZWRjY2M5YmFhNTg5QHBvc3RhbC5kdmlzaW9uLm9yZz4=
>> YWRlbGJyZWNodC9zZXZkZXNrIDlmNDZiYzViYmE4ZDA1MDZiMDI4YzUzMTljNzY5NTIw
<< 235 Granted for postal-mail-sever/credential`


SSL is not:

`ERROR: An error occurred while attempting to establish an SSL or TLS connection.`

Devices (printers with scan-to-mail) with STARTTLS do not work - limited log capabilities there.

This is the result from "openssl s_client -starttls smtp -crlf -connect postal.my-domain.com:25", run on a different server:

`CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = postal.my-domain.com
verify return:1
---
Certificate chain
 0 s:CN = postal.my-domain.com
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 29 10:50:58 2024 GMT; NotAfter: May 29 10:50:57 2024 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEJTCCAw2gAwIBAgISBGBlc3QdN7kcgppeNrA6IEWRMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yNDAyMjkxMDUwNThaFw0yNDA1MjkxMDUwNTdaMB0xGzAZBgNVBAMT
EnBvc3RhbC5kdmlzaW9uLm9yZzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOw1
Lh25bXePjzUvTd+HklIOi9ZLqn6kkP+6xZO0sSOaOIpX2ROIBuzQKBWrZf7n2WyF
T9rvX+Rg+DxGIEQzxaKjggITMIICDzAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYw
FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFH5+
OgworAy6eEQhEiS/3iWlbvPmMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYfr52L
FMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8ubGVu
Y3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMB0GA1Ud
EQQWMBSCEnBvc3RhbC5kdmlzaW9uLm9yZzATBgNVHSAEDDAKMAgGBmeBDAECATCC
AQMGCisGAQQB1nkCBAIEgfQEgfEA7wB2AEiw42vapkc0D+VqAvqdMOscUgHLVt0s
gdm7v6s52IRzAAABjfS0EpEAAAQDAEcwRQIgBCLFStiEyF/6rqoVly+BYlGlX9qL
xLPLDH5d4qS47jwCIQCLhKthnfZ6igdwVsfoJO0U5YsaThwajJkDUqPI8sKdsgB1
AO7N0GTV2xrOxVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7WbAAABjfS0EpMAAAQDAEYw
RAIgQ97UKX9qAGVfEp30FR/zv0T+jVlROqoJQY5VO7UPs/MCIGJ45A6be1A+E0RI
bbY4S5Xjn8+Wl9WOEvbADn3u7vGlMA0GCSqGSIb3DQEBCwUAA4IBAQBQrEPhnVZ5
eGwt1OomoZMp6Z7PJd6jbuBrgXJAwAI0DNynccmCtQfcEpParYNONP80r4aiTxeL
FRvOgijnTwrKjxX3OvaqKmJsJOfuuNJasmSuW6KK6zgUDM3606EzUhCUQFrvBAIt
e0In1jKhuwwcVaQraEGeKNsvo1rxSetw9JNtBIricLu4tte+DKCH8WAvb5nwTbzO
G63+NtmEE/GLO4C0HAWSbYoEtqcx63nZqQGFbnxgl1bGI1k2DGfQ0v2ADczrs4+1
DV6Bt5MjAX0DX3uF35Hmsmre5bBMBy8ireInAwwb9dyr+V5AxaKUo41nSMJBo4UX
qaXvXfG8MGb5
-----END CERTIFICATE-----
subject=CN = postal.my-domain.com
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2886 bytes and written 437 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
250 AUTH CRAM-MD5 PLAIN LOGIN
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 003493CA6DE7DCD27E990823955AA3CE2F6F8FE69342902B7E355F752222D4FC
    Session-ID-ctx: 
    Resumption PSK: C471212E918DE31CAE3EB0774DE4B1FF04C31AEFD851444ADFF7197597F8FE42CACC3930EE6FC15C8BB3BBEA3A5198AF
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - fe d0 9e 0b 59 e8 a6 82-6d 9b 6e 13 24 4f 41 ef   ....Y...m.n.$OA.
    0010 - 33 ef d7 fc 6f 20 d4 45-cf 90 cc d1 0b d8 bc a2   3...o .E........
    0020 - ab c2 f4 32 ad 74 63 72-0c 01 67 ce b1 8b 21 9c   ...2.tcr..g...!.
    0030 - 70 f2 9f f4 a9 0c 91 cc-fb b4 c1 6b db c7 52 5e   p..........k..R^
    0040 - e0 fd b3 1d 31 63 3a 72-7f 37 8f 16 fe 36 1a c8   ....1c:r.7...6..
    0050 - 33 57 a2 00 ff 08 39 93-f4 8d df 16 e2 46 7d 1d   3W....9......F}.
    0060 - 28 5b e9 17 29 61 1d 93-7e 24 22 98 0e 9f c7 65   ([..)a..~$"....e
    0070 - 78 79 17 2e 00 00 91 30-d6 30 06 a2 98 1c 8e 33   xy.....0.0.....3
    0080 - a9 f8 8e 7f 01 66 de a0-fa f7 bf 80 97 96 98 34   .....f.........4
    0090 - 28 9b 0b 50 8c 4d ec 5f-c9 68 d4 30 f9 2f f8 14   (..P.M._.h.0./..
    00a0 - c3 55 fc d1 6c 07 df 75-53 a5 ce d9 57 cc 80 54   .U..l..uS...W..T
    00b0 - 21 b8 ab a1 06 f6 89 31-b4 5d 9b 88 b5 1a e2 04   !......1.]......

    Start Time: 1709211887
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: C84208C84AEDBE91B8A5EDB5D1AB4B7642C8D13F73975EED86BC635E316645BA
    Session-ID-ctx: 
    Resumption PSK: 8C896B81DD53F042647A654A61BABCEEBE5C9B5283C7701179C969339213D8F362E16507DDBD08143D6CCE4F284ACD99
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - fe d0 9e 0b 59 e8 a6 82-6d 9b 6e 13 24 4f 41 ef   ....Y...m.n.$OA.
    0010 - bb 84 24 de 5a dd f3 2f-67 24 50 a5 2a 12 2f f9   ..$.Z../g$P.*./.
    0020 - 30 1a d4 08 9d e2 a9 29-1a 2b f0 1e 57 7c 61 28   0......).+..W|a(
    0030 - 6b 9a 74 36 fd db d2 ed-ec c5 0f 0d 8b ef a1 b9   k.t6............
    0040 - c8 55 72 70 cf 9d 69 dd-c7 3b f6 ed 58 ab 7d ba   .Urp..i..;..X.}.
    0050 - 4c 1a 7f 65 50 78 d2 96-8f f4 cf 14 0b 3d b6 cf   L..ePx.......=..
    0060 - 8e 89 00 0b 2f 00 82 c3-da d8 4d 1f b5 9d 52 ad   ..../.....M...R.
    0070 - 60 f3 bd 86 bf 54 fa 59-e1 60 3c a9 a2 ab ab a6   `....T.Y.`<.....
    0080 - d8 0b 5d a9 1e d2 e5 2a-e5 3a dc bc 71 4f d4 ed   ..]....*.:..qO..
    0090 - 49 22 d2 ab fd 4c 1e 7b-be 91 09 01 20 ab d6 a3   I"...L.{.... ...
    00a0 - 6e 8c 84 41 71 fd a3 39-1d 58 4d 5b 2d e4 24 19   n..Aq..9.XM[-.$.
    00b0 - 78 7a cc 7f dc 4e f1 e2-fb 7c bf d6 c3 7a 6b 5b   xz...N...|...zk[

    Start Time: 1709211888
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK`

(the command stops after that - dont know if this is supposed to)

Can you give me further assistance? Thank you very much

**Comment by bitbay** [comment]
For future googlers on how to use `caddy`'s autorenewed certificates with `postal` TLS.

Evaluating different approaches, like
* using `certbot` running on docker host
  * mapped volume for cert files inside `caddy`+`postal`
  * `cron` with script to reload both `caddy` and `postal` on renewal with `--renew-hook`
* using `caddy` with `caddy-events-exec` module and on renewal
  * scripted as explained [here](https://caddy.community/t/event-dispatching-system-for-caddy/20825/3)
  * [named pipes](https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container) for container/host communication

Since `caddy` has a zero-downtime if it handles certificate renewals itself (citation needed), i wanted to at least have that, only having to restart the `postal-smtp` - still seems like an overkill for just re-reading values from files, but until we have an endpoint to force-reload them, sticking with restart.

So the easiest way for me to set this up was
1. To use `/var/run/docker.sock` for API calls to docker from inside the container [docker-socket-file-for-ipc](https://lobster1234.github.io/2019/04/05/docker-socket-file-for-ipc/).
2. Forcing `caddy` to [use only `letsencrypt`](https://caddy.community/t/how-to-disable-zerossl/23644/7) and discard `zerossl` fallback by using explicit `acme_ca`. This way the file's names will be predictable.
3. Sharing those files between `caddy` and `postal`
4. Use a custom built `caddy` image with [`caddy-events-exec`](https://github.com/mholt/caddy-events-exec) and `curl`.
---
The `build/Dockerfile` for `caddy`
```Dockerfile
FROM caddy:2.8.4-builder AS builder

# add caddy-events-exec module
RUN xcaddy build \
    --with github.com/mholt/caddy-events-exec

FROM caddy:2.8.4

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
# install curl
RUN apk --no-cache add curl
```
The `Caddyfile`
```
{
  debug
    #production
    acme_ca https://acme-v02.api.letsencrypt.org/directory
    #staging
    # acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
    email your@email.com

  events {
    #call docker restart on container "postal-smtp-1"
    on cert_obtained exec curl --unix-socket /var/run/docker.sock -X POST http://dck/containers/postal-smtp-1/restart
  }
}
```
The `docker-compose.yml` (only necesarry additions here)
```yaml
services:
  proxy:
    image: caddy-custom:2.8.4-alpine
    build:
      context: ./build/
    container_name: postal-caddy
    restart: unless-stopped
    network_mode: host
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # read-only socket for IPC
        - /opt/postal/caddy-data:/data:rw
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
  
  smtp:
    image: ghcr.io/postalserver/postal:3.3.4
    user: "root:root" # needed for reading cert/key files
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/caddy-data:/data:ro
    restart: unless-stopped
    depends_on:
      - mariadb
      - proxy
```

Not the most elegant way (needs root, socket, etc), but should do the job for now (i'll let You all know in 2 months from now)  
  
---
Has some room to improve:
* use a script callback on `caddy` event, that could use both `zerossl` and `letsencrypt`. The script should use the cert and key file locations received in the event to change the `/opt/postal/config/postal.yml` file to point to the right ones, then issue the `curl` POST
* `postal-smtp` could expose some way to only reload the keys and not doing a full-blown stop-start cycle for maximum uptime (letsencrypt certificates by default renew a lot)
